"""table picture

Revision ID: 1756054fa8c0
Revises: bd7a894a7567
Create Date: 2023-07-28 15:17:07.171988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1756054fa8c0'
down_revision = 'bd7a894a7567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('cart',
    sa.Column('user_cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_cart_id'], ['user.id'], )
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['picture_id'], ['picture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture_format')
    op.drop_table('picture')
    op.drop_table('cart')
    op.drop_table('followers')
    # ### end Alembic commands ###
